I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 316, in script
    l "히히히, 내꺼야~" (가져간다)
  File "game/script.rpy", line 316, in <module>
    l "히히히, 내꺼야~" (가져간다)
NameError: name '가져간다' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 316, in script
    l "히히히, 내꺼야~" (가져간다)
  File "C:\Users\Home\Desktop\renpy-8.3.7-sdk\renpy\ast.py", line 2586, in execute
    Say.execute(self)
  File "C:\Users\Home\Desktop\renpy-8.3.7-sdk\renpy\ast.py", line 609, in execute
    args, kwargs = self.arguments.evaluate()
  File "C:\Users\Home\Desktop\renpy-8.3.7-sdk\renpy\parameter.py", line 503, in evaluate
    value = renpy.python.py_eval(v, locals=scope)
  File "C:\Users\Home\Desktop\renpy-8.3.7-sdk\renpy\python.py", line 1218, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Home\Desktop\renpy-8.3.7-sdk\renpy\python.py", line 1211, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 316, in <module>
    l "히히히, 내꺼야~" (가져간다)
NameError: name '가져간다' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.7.25031702
Project_Horror 1.0
Mon Apr  7 12:34:22 2025
